### ISSUE TITLE
Crash when trying to log in

### ISSUE THREAD

**Issue by Tosox** [ClementJ18/moddb#57]
I noticed a crash when trying to `moddb.login`

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\moddb\pages\base.py", line 57, in __init__
    re.search(r"siteareaid=(\d*)", html.find("a", class_=["reporticon"])["href"])[1]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\moddb\pages\base.py", line 61, in __init__
    self.id = int(html.find("input", attrs={"name": "siteareaid"})["value"])
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\moddb_new_addon_comments.py", line 77, in main
    moddb.login('username', 'password')
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\moddb\base.py", line 176, in login
    return Member(get_page(f"{BASE_URL}/members/{username.replace('_', '-')}"))
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\moddb\pages\entity.py", line 333, in __init__
    super().__init__(html, SearchCategory.members)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\moddb\pages\base.py", line 255, in __init__
    super().__init__(html)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\moddb\pages\base.py", line 64, in __init__
    self.id = int(html.find("meta", property="og:image")["content"].split("/")[-2])
TypeError: 'NoneType' object is not subscriptable
```

When logging in the script will load and return the member user page. The `id` of `BaseMetaClass` will get loaded like this:
```py
try:
  self.id = int(
    re.search(r"siteareaid=(\d*)", html.find("a", class_=["reporticon"])["href"])[1]
  )
except TypeError:
  try:
    self.id = int(html.find("input", attrs={"name": "siteareaid"})["value"])
  except (AttributeError, TypeError):
    # really scratching the bottom here but a lot of "official" groups don't have the regular ID
    self.id = int(html.find("meta", property="og:image")["content"].split("/")[-2])
```

This means that if the user is logged in getting the id will always fall back to `self.id = int(html.find("meta", property="og:image")["content"].split("/")[-2])`. But it looks like `og:image` only exists if the user set a profile image, otherwise `html.find` will return `None`.

I found that the user id can still be found by searching for `https://www.moddb.com/html/scripts/autocomplete.php?a=mentions&p=home&l=6&u=<userid>` on the user page. The results will be found in a script tag.

**Comment by ClementJ18** [comment]
Added this in the latest release but forgot to mention it.
